// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/sampalm/goa/cellar/design
// --out=$(GOPATH)\src\github.com\sampalm\goa\cellar
// --version=v1.3.1

package app
